### PR TITLE
0.1.0

### PR DESCRIPTION
**Pull request by aniruddh-1**
Hello Sir, made the changes as demanded in Contributing.md file on the server, please check and let me know if/any further changes are required. Thanks for your Patience Sir.

### CODE REVIEW

**Review by AdamMiltonBarker — COMMENTED** [review]
Hi thanks for the quick update, there was no need to create a new pull request :) I will cancel your last one. 

According to the contributing guide the first point of call would be to create a feature proposal, we will skip this here, but please remember for the future. 

Some changes still required sorry :) 

- You can remove the information added to the main repository README, this would go in your project README after the link to the installation documentation. 
- In that information you say "You can also download the dataset directly from above link or can go through our dataset where we have indexed all the images and converted them into same format(PNG)."  You are free to add the dataset only if you have written permission from the owners, if not then a link and attribution is required.  
- The installation document does not make sense, users would need to clone the repository before being able to run the scripts. Just to confirm, are those all of the installation steps? I don't see anything about preparing/placing the data etc. The purpose of the installation document is to provide all and any required information so that everything is installed, rather than linking to other tutorials the purpose is all of the steps are highlighted in our documentation. A good example is https://github.com/LeukemiaAiResearch/HIAS-Hospital-Intelligent-Automation-System/blob/master/Documentation/Installation/Installation.md 
- Please remember the tutorials are suppose to be high level and complete, I see you added you the classes to the classes directory, but how are these run? In what order are the scripts executed? What are the data processing steps, where should the user place the dataset so that the program can access it etc ? A complete tutorial would like the following and would include a primary Python file in the core of your project which would be executed. https://github.com/AdamMiltonBarker/ALL-Detection-System-2020/tree/master/CNN
- I also provided our core Helpers file so you could integrate the logging into the system.  
- The confs file should contain any configurable settings and a description should be included in the documentation. 

I have tried to be as descriptive as possible, our work and tutorials have to be professional and correctly documented.  Thank you for your hard work so far if you have any questions please reach out, the first pull request is always the hardest :)  Once these are completed hopefully we can merge your pull request :)

**Comment by AdamMiltonBarker** [comment]
Sorry buddy noticed another thing; "so you can also contribute by sharing any ideas or providing more dataset for this repository by sending the information on our email." This is said directly above the instructions for contributing and also links to the repo not an email. You can say follow the instructions for contributing below or similar.

**Comment by AdamMiltonBarker** [comment]
Hi mate thanks for the quick reponse. I have been checking just a few things to sort out.

- In the installation file the Developer Forks section has been cut from the bottom of the cloning section.
- The clone section needs to be above the first script command or it doesn't make sense.
- Repository Motivation should be named Project Motivation and references to repository should be project. This section should also be in the README, only installation steps in the installation files.
- There is a broken image in the installation file.

With those fixed I think we are good to go :) Thank you again mate it is looking really good :)

**Comment by aniruddh-1** [comment]
hello sir, I have solved 2nd, 3rd and 4th point.
Yeah there is a developer fork in the cloning section, what do you need me to do with it?
Please check and let me know for further changes if/any required...

**Comment by AdamMiltonBarker** [comment]
HI mate Developer Forks should be directly below Clone the repository. Once that is done we can merge :) Thank you again for being so quick in making the changes :)

**Comment by aniruddh-1** [comment]
Is it in right structure now?

**Comment by AdamMiltonBarker** [comment]
I noticed some other changes but I will do them the next time I do a push. Thank you for your hard work and speed at doing the updates, you know pretty much all of the layout now so next time will be a lot quicker :) Congratulations on your first merge 🥇 Tomorrow we will do some promotion.

**Pull request merged**
