### PR TITLE
Updated CNN Model for COVID-19 Pneumonia Detection using CT Scans

### PR DESCRIPTION
**Pull request by aniruddh-1**

### CODE REVIEW

**Review by AdamMiltonBarker — CHANGES_REQUESTED** [review]
Hi mate, thank you for submitting a pull request. Apologies our template structure and contributing guides were not added to this repository yet. 

Please could you follow our contributing guide. Many thanks.

https://github.com/COVID-19-AI-Research-Project/COVID19-Medical-Support-System-Server/blob/master/CONTRIBUTING.md

**Comment by aniruddh-1** [comment]
Hello Sir, I followed the contributing guide, have some doubts for improving the repository:
1. Would I have to provide the install dependencies of tensorflow 2.0, python 3.6 etc in the Documentation/Installation directory or not provide in repo?
2. I will be making 3 directories as: Media, dataset, scripts in master branch, is that fine or need any modifications?
3. What further commits are you expecting in my master branch?

Sorry but this is my first Pull requests, I don't know what exact ways a repo format should be made for a CNN model to make it understandable for the others.

**Comment by AdamMiltonBarker** [comment]
> Hello Sir, I followed the contributing guide, have some doubts for improving the repository:
> 
> 1. Would I have to provide the install dependencies of tensorflow 2.0, python 3.6 etc in the Documentation/Installation directory or not provide in repo?
> 2. I will be making 3 directories as: Media, dataset, scripts in master branch, is that fine or need any modifications?
> 3. What further commits are you expecting in my master branch?
> 
> Sorry but this is my first Pull requests, I don't know what exact ways a repo format should be made for a CNN model to make it understandable for the others.

Hi buddy, to make it easier I will add the template structure now :) 

Our purpose is to make our technology open to everyone, including non devs that may want to learn. Also our work will be used within our student program. Although our process is not entirely complete, the general idea is that the Github tutorial and installation documentation will be high level. Then we will use our Medium account write more in-depth, and low level articles etc. https://medium.com/leukemiaairesearch

 We are currently writing our first paper, in the future there will be opportunities to co-author papers and books etc. 

The best working example of our repositories is: https://github.com/COVID-19-AI-Research-Project/COVID19-Medical-Support-System-Server/tree/0.3.0

1. You should provide any related installation steps in an installation tutorial and scripts is possible yes mate.
2. I will provide the template repository now, you will add your project in the Projects -> 1 directory. Inside there you should follow the structure and layout of the provided example above. Directories used should stay the same, the README header/footer should be the same as the repository README and the layout / styling / sections etc should remain uniform. This is so that for our end users, our working process is always familiar. 
3. Hopefully the above answered this :) 

Don't worry I know this is your first time and we are still adapting :)

**Comment by AdamMiltonBarker** [comment]
Hi @aniruddh-1 I have added the core structure, the current dev branch is 0.1.0, I have updated your pull request to point to the correct branch. 

You can add your project in the Projects/1 directory: https://github.com/COVID-19-AI-Research-Project/AI-Classification/tree/0.1.0/Projects/1 

Please also see the new contributing guide as I have included a lot more information. https://github.com/COVID-19-AI-Research-Project/AI-Classification/blob/0.1.0/CONTRIBUTING.md

Thank you for waiting while I got the repository up to date. If you have any questions please let me know.

**Comment by AdamMiltonBarker** [comment]
Closing as duplicate pull request. https://github.com/COVID-19-AI-Research-Project/AI-Classification/pull/3 is the current pull request.

**Pull request closed without merging**
